
# threadripper:
principal_input_sample_metadata: "resources/metadata_v1.6.tsv"
principal_input_proteome_amino_acid_sequences: "/spaceface/projects/supacow/results/holodoublevu_heavy_resources/supacow_amino_acid.faa"
principal_input_proteome_intensities: "/spaceface/projects/supacow/results/holodoublevu_heavy_resources/proteomics_long_v2.rds"
principal_input_proteome2genome_mapping: "/spaceface/projects/supacow/results/holodoublevu_heavy_resources/01_map_proteome2samples_c6_v4.rds.gz"
kegg_data: "resources/kegg_data.tsv"
eggnog_database: "/spaceface/shared_databases/asscom2_v2.5.5+/eggnog/"



# thylakoid:
principal_input_sample_metadata: "resources/metadata_v1.6.tsv"
principal_input_proteome_amino_acid_sequences: "/home/thylakoid/PhD/26_proteomics_analysis/holodoublevu/heavy_resources/supacow_amino_acid.faa"
principal_input_proteome_intensities: "/home/thylakoid/PhD/26_proteomics_analysis/proteomic_integration/results/00_uniform_data/proteomics_long_v2.rds"
principal_input_proteome2genome_mapping: "/home/thylakoid/PhD/26_proteomics_analysis/proteomic_integration/results/01_maps/01_map_proteome2samples_c6_v4.rds.gz"
kegg_data: "resources/kegg_data.tsv"
eggnog_database: "/mnt/evo/databases/cm2_2.11.1/eggnog"




# Filtered out samples are not included in the imputation_group dictionary.
imputation_group:
  luing: [D06T6S, D08T6S, D16T6S, D25T6S, D28T1S, D28T2S, D28T3S, D28T4S, D28T5S, D28T6S, D29T6S, D35T6S, D51T1S, D51T2S, D51T3S, D51T4S, D51T5S, D51T6S, D60T6S, D61T6S, D76T6S, L06T6R, L08T6R, L16T6R, L25T6R, L28T6R, L29T6R, L35T6R, L42T6R, L51T6R, L60T6R, L61T6R, L76T6R, W06T6R, W08T6R, W16T6R, W25T6R, W29T6R, W35T6R, W42T6R, W51T6R, W60T6R, W61T6R, W76T6R]
  both: [D01T6S, L01T6R, D01T1S, D01T3S, D01T4S, D01T2S, D01T5S, D02T6S, W02T6R, L02T6R, D02T1S, D02T2S, D02T3S, D02T4S, D02T5S, D15T6S, W15T6R, L15T6R, D21T6S, W21T6R, L21T6R, D43T6S, W43T6R, L43T6R, W45T6R, L45T6R, D48T6S, W48T6R, L48T6R, D55T6S, W55T6R, L55T6R, D55T1S, D55T2S, D55T3S, D55T4S, D55T5S, D59T6S, W59T6R, L59T6R, D63T6S, W63T6R, L63T6R, D67T6S, W67T6R, L67T6R, D67T1S, D67T2S, D67T3S, D67T4S, D67T5S, D75T6S, W75T6R, L75T6R, D06T6S, W06T6R, L06T6R, D08T6S, W08T6R, L08T6R, D16T6S, W16T6R, L16T6R, D25T6S, W25T6R, L25T6R, D28T6S, L28T6R, D28T1S, D28T3S, D28T4S, D28T5S, D28T2S, D29T6S, W29T6R, L29T6R, D35T6S, W35T6R, L35T6R, W42T6R, L42T6R, D51T6S, W51T6R, L51T6R, D51T1S, D51T2S, D51T3S, D51T4S, D51T5S, D60T6S, W60T6R, L60T6R, D61T6S, W61T6R, L61T6R, D76T6S, W76T6R, L76T6R]
  aberdeen: [D01T6S, L01T6R, D01T1S, D01T3S, D01T4S, D01T2S, D01T5S, D02T6S, W02T6R, L02T6R, D02T1S, D02T2S, D02T3S, D02T4S, D02T5S, D15T6S, W15T6R, L15T6R, D21T6S, W21T6R, L21T6R, D43T6S, W43T6R, L43T6R, W45T6R, L45T6R, D48T6S, W48T6R, L48T6R, D55T6S, W55T6R, L55T6R, D55T1S, D55T2S, D55T3S, D55T4S, D55T5S, D59T6S, W59T6R, L59T6R, D63T6S, W63T6R, L63T6R, D67T6S, W67T6R, L67T6R, D67T1S, D67T2S, D67T3S, D67T4S, D67T5S, D75T6S, W75T6R, L75T6R]

# just both, for quick testing
imputation_group:
  both: [D01T6S, L01T6R, D01T1S, D01T3S, D01T4S, D01T2S, D01T5S, D02T6S, W02T6R, L02T6R, D02T1S, D02T2S, D02T3S, D02T4S, D02T5S, D15T6S, W15T6R, L15T6R, D21T6S, W21T6R, L21T6R, D43T6S, W43T6R, L43T6R, W45T6R, L45T6R, D48T6S, W48T6R, L48T6R, D55T6S, W55T6R, L55T6R, D55T1S, D55T2S, D55T3S, D55T4S, D55T5S, D59T6S, W59T6R, L59T6R, D63T6S, W63T6R, L63T6R, D67T6S, W67T6R, L67T6R, D67T1S, D67T2S, D67T3S, D67T4S, D67T5S, D75T6S, W75T6R, L75T6R, D06T6S, W06T6R, L06T6R, D08T6S, W08T6R, L08T6R, D16T6S, W16T6R, L16T6R, D25T6S, W25T6R, L25T6R, D28T6S, L28T6R, D28T1S, D28T3S, D28T4S, D28T5S, D28T2S, D29T6S, W29T6R, L29T6R, D35T6S, W35T6R, L35T6R, W42T6R, L42T6R, D51T6S, W51T6R, L51T6R, D51T1S, D51T2S, D51T3S, D51T4S, D51T5S, D60T6S, W60T6R, L60T6R, D61T6S, W61T6R, L61T6R, D76T6S, W76T6R, L76T6R]
  
