

principal_input_sample_metadata: "~/PhD..."
principal_input_proteome_amino_acid_sequences: "~/PhD..."
principal_input_proteome_intensities: "~/PhD.."
principal_input_proteome-to-genome_mapping: "~/Phd.."

